title: Elizabeth Moreno 
logo: "images/profile photo.jpg" # your photo (or logo) here
description: 
  Jr Data Analyst.
  <br><br>
Data Cleaning, Data Visualization, Excel, Power BI, Tableu, SQL, R.
  <br><br>
  <a href="https://www.linkedin.com/in/elizabeth-moreno24/">View My LinkedIn Profile</a> 
   <br><br>
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
gem "github-pages", group: :jekyll_plugins


