title: Elizabeth Moreno # your name (or website title) here
logo: "images/profile photo.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <Data Analyst Jr.>
  <br><br>
<Data Cleaning, Data Visualization, Excel, Power BI, Tableu, SQL, R.>
  <br><br>
  <a href="https://www.linkedin.com/in/elizabeth-moreno24/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme

